import IconDashboardUrl from './icon_dashboard.svg?url';
import IconDatasetUrl from './icon_dataset.svg?url';
import IconInfraManagementUrl from './icon_infraManagement.svg?url';
import IconKnowledgeBaseUrl from './icon_knowledgeBase.svg?url';
import IconLearningUrl from './icon_learning.svg?url';
import IconMemberManagementUrl from './icon_memberManagement.svg?url';
import IconModelUrl from './icon_model.svg?url';
import IconPromptUrl from './icon_prompt.svg?url';
import IconServiceUrl from './icon_service.svg?url';
import IconWorkflowUrl from './icon_workflow.svg?url';

export const IconDashboard = IconDashboardUrl;
export const IconDataset = IconDatasetUrl;
export const IconInfraManagement = IconInfraManagementUrl;
export const IconKnowledgeBase = IconKnowledgeBaseUrl;
export const IconLearning = IconLearningUrl;
export const IconMemberManagement = IconMemberManagementUrl;
export const IconModel = IconModelUrl;
export const IconPrompt = IconPromptUrl;
export const IconService = IconServiceUrl;
export const IconWorkflow = IconWorkflowUrl;
